version: "3.7"

services:
  server:
    build: ./
    container_name: server_container
    environment:
      - DB_USER=reservation
      - DB_HOST=db
      - DB_NAME=reservation
      - DB_PASSWORD=password
      - DB_PORT=5432
    ports:
        - 3000:3000
    depends_on: 
          - db
    restart: always
  db:
    image: postgres
    container_name: db_container
    volumes:
      - ./server/db-init/1-init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./server/db-init/2-tables.sql:/docker-entrypoint-initdb.d/2-tables.sql
      - ./server/db-data/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=reservation
      - POSTGRES_PASSWORD=password
    restart: always